theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/duck_liu.jpg
description:
  "PhD Student\n
  396 Engineering VI\n
  Computer Science Department\n
  University of California, Los Angeles\n
  Los Angeles, CA 90095\n
  Email: yxu [at] cs.ucla.edu"
