theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/duck_liu.jpg
description: "PhD Student
  <br>Computer Science Department
  <br>University of California, Los Angeles
  <br>Los Angeles, CA 90095

  <br>Office: 396 Engineering VI
  <br>Email: yxu [at] cs [dot] ucla [dot] edu"
