theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/portrait.jpg
description: "
  <br><i class='fas fa-map-marker-alt'></i> 396 Eng VI, UCLA
  <br><i class='fas fa-envelope'></i><a href=\"mailto:yxu@cs.ucla.edu\"> Email</a>
  <br><i class='fab fa-google'><a href=\"https://scholar.google.com/citations?user=ua-jnqEAAAAJ&hl=en\"></i> Google Scholar</a>
  <br><i class='fab fa-linkedin'><a href=\"https://www.linkedin.com/in/yifei-xu-7046131b3/\"></i> LinkedIn</a>
  <br><i class='fab fa-github'></i><a href=\"https://github.com/AlanNPC\"> GitHub</a>
  <br><i class='fas fa-file-alt'></i><a href=\"files/Resume_YifeiXu_20231030.pdf\"> CV</a>"

