theme: minimal-mistakes-jekyll
title: Yifei Xu
logo: /images/portrait.jpg
description: "PhD Student
  <br>Computer Science Department
  <br>University of California, Los Angeles
  <br>Los Angeles, CA 90095
  <br>
  <br>Office: 396 Engineering VI
  <br>Email: yxu [at] cs [dot] ucla [dot] edu
  <br>
  <br><a href=\"https://scholar.google.com/citations?user=ua-jnqEAAAAJ&hl=en\">Google Scholar</a>
  <br><a href=\"https://www.linkedin.com/in/yifei-xu-7046131b3/\">Linkedin</a>
  <br><a href=\"https://github.com/AlanNPC\">Github</a>
  <br><a href=\"files/Resume_YifeiXu_20231030.pdf\">CV</a>"

classes: wide
