theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/duck_liu.jpg
description: |
  PhD Student \n\n

  396 Engineering VI \n\n

  Computer Science Department \n\n

  University of California, Los Angeles \n\n

  Los Angeles, CA 90095 \n\n

  Email: yxu [at] cs.ucla.edu

  