theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/duck_liu.jpg
description: "PhD Student
  \n396 Engineering VI
  \nComputer Science Department
  \nUniversity of California, Los Angeles
  \nLos Angeles, CA 90095
  \nEmail: yxu [at] cs.ucla.edu"
