theme: jekyll-theme-minimal
title: Yifei Xu
logo: /images/portrait.jpg
description: "
  <br>396 Eng VI, UCLA <i class='fas fa-map-marker-alt'></i>
  <br><a href=\"mailto:yxu@cs.ucla.edu\"><i class='fas fa-envelope'></i> Email</a>
  <br><a href=\"https://scholar.google.com/citations?user=ua-jnqEAAAAJ&hl=en\"><i class='fab fa-google'></i> Google Scholar</a>
  <br><a href=\"https://www.linkedin.com/in/yifei-xu-7046131b3/\"><i class='fab fa-linkedin'></i> LinkedIn</a>
  <br><a href=\"https://github.com/AlanNPC\"><i class='fab fa-github'></i> GitHub</a>
  <br><a href=\"files/Resume_YifeiXu_20231030.pdf\"><i class='fas fa-file-alt'></i> CV</a>"

